color: null
fieldLayouts:
  f6df1b18-a5d7-4bb6-b3f1-df14de36df46:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-30T13:38:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1d1066c5-a235-4b95-b769-ca31d14ff483
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T13:40:27+00:00'
            elementCondition: null
            fieldUid: 2dc0eec0-8212-489c-92c3-5ef43da4bf6f # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94061721-49f3-43f3-aeb9-ef102fd27f43
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cb0214a-dee7-4c1e-b3f8-29519dbc416f
        userCondition: null
handle: subhead
hasTitleField: false
icon: ''
name: Subhead
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
