color: null
fieldLayouts:
  1f6ab771-bb64-4864-a666-2074c232c5a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-30T13:39:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c17c88fd-366f-4921-afbe-bf2cbbf15a36
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T13:41:20+00:00'
            elementCondition: null
            fieldUid: 871e17fd-93c5-4f99-b004-ebbd5303689b # Article Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d847eee-7826-49b9-9156-514fcd6290db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85a51592-60ea-4318-bbd5-3be118b97280
        userCondition: null
handle: text
hasTitleField: false
icon: ''
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
