baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft 5caffold'
primary: true
siteGroup: a033033c-2320-4124-996c-2e6e2c1b2869 # Craft 5caffold
sortOrder: 1
