altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  223262e3-ab4c-4fc3-8ccf-a53023bae4a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-26T17:28:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7b0fa929-d748-4dd1-8b17-8e3ddcd3ed56
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0903bb8-20dd-4582-b422-be90843b70bf
        userCondition: null
fs: public
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: public
transformSubpath: ''
