defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3eed0c77-3b75-46cd-8e31-351f3c83f416 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - 'http://localhost:3000/api/preview?entryUid={canonicalUid}'
propagationMethod: all
siteSettings:
  2eb36cc0-a60a-4071-a815-ce808da649b2: # Template
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
